//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConceptMappingChangeCount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConceptMappingChangeCount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="source_code_system_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="source_code_system_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="target_code_system_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="target_code_system_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codes_added" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codes_removed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codes_modified" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConceptMappingChangeCount", propOrder = {
    "sourceCodeSystemId",
    "sourceCodeSystemName",
    "targetCodeSystemId",
    "targetCodeSystemName",
    "codesAdded",
    "codesRemoved",
    "codesModified"
})
public class ConceptMappingChangeCount
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "source_code_system_id", required = true)
    protected String sourceCodeSystemId;
    @XmlElement(name = "source_code_system_name", required = true)
    protected String sourceCodeSystemName;
    @XmlElement(name = "target_code_system_id", required = true)
    protected String targetCodeSystemId;
    @XmlElement(name = "target_code_system_name", required = true)
    protected String targetCodeSystemName;
    @XmlElement(name = "codes_added")
    protected int codesAdded;
    @XmlElement(name = "codes_removed")
    protected int codesRemoved;
    @XmlElement(name = "codes_modified")
    protected int codesModified;

    /**
     * Gets the value of the sourceCodeSystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceCodeSystemId() {
        return sourceCodeSystemId;
    }

    /**
     * Sets the value of the sourceCodeSystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceCodeSystemId(String value) {
        this.sourceCodeSystemId = value;
    }

    public boolean isSetSourceCodeSystemId() {
        return (this.sourceCodeSystemId!= null);
    }

    /**
     * Gets the value of the sourceCodeSystemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceCodeSystemName() {
        return sourceCodeSystemName;
    }

    /**
     * Sets the value of the sourceCodeSystemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceCodeSystemName(String value) {
        this.sourceCodeSystemName = value;
    }

    public boolean isSetSourceCodeSystemName() {
        return (this.sourceCodeSystemName!= null);
    }

    /**
     * Gets the value of the targetCodeSystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetCodeSystemId() {
        return targetCodeSystemId;
    }

    /**
     * Sets the value of the targetCodeSystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetCodeSystemId(String value) {
        this.targetCodeSystemId = value;
    }

    public boolean isSetTargetCodeSystemId() {
        return (this.targetCodeSystemId!= null);
    }

    /**
     * Gets the value of the targetCodeSystemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetCodeSystemName() {
        return targetCodeSystemName;
    }

    /**
     * Sets the value of the targetCodeSystemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetCodeSystemName(String value) {
        this.targetCodeSystemName = value;
    }

    public boolean isSetTargetCodeSystemName() {
        return (this.targetCodeSystemName!= null);
    }

    /**
     * Gets the value of the codesAdded property.
     * 
     */
    public int getCodesAdded() {
        return codesAdded;
    }

    /**
     * Sets the value of the codesAdded property.
     * 
     */
    public void setCodesAdded(int value) {
        this.codesAdded = value;
    }

    public boolean isSetCodesAdded() {
        return true;
    }

    /**
     * Gets the value of the codesRemoved property.
     * 
     */
    public int getCodesRemoved() {
        return codesRemoved;
    }

    /**
     * Sets the value of the codesRemoved property.
     * 
     */
    public void setCodesRemoved(int value) {
        this.codesRemoved = value;
    }

    public boolean isSetCodesRemoved() {
        return true;
    }

    /**
     * Gets the value of the codesModified property.
     * 
     */
    public int getCodesModified() {
        return codesModified;
    }

    /**
     * Sets the value of the codesModified property.
     * 
     */
    public void setCodesModified(int value) {
        this.codesModified = value;
    }

    public boolean isSetCodesModified() {
        return true;
    }

}
