//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="value_set_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clear_source_value_set" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="force_delete_stale_codes" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="create_new_version" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="code" type="{urn://cts.hl7.org/types}CD" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "valueSetId",
    "clearSourceValueSet",
    "forceDeleteStaleCodes",
    "createNewVersion",
    "code"
})
@XmlRootElement(name = "ConceptsToUpload")
public class ConceptsToUpload
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "value_set_id", required = true)
    protected String valueSetId;
    @XmlElement(name = "clear_source_value_set")
    protected boolean clearSourceValueSet;
    @XmlElement(name = "force_delete_stale_codes")
    protected Boolean forceDeleteStaleCodes;
    @XmlElement(name = "create_new_version")
    protected Boolean createNewVersion;
    protected List<CD> code;

    /**
     * Gets the value of the valueSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueSetId() {
        return valueSetId;
    }

    /**
     * Sets the value of the valueSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueSetId(String value) {
        this.valueSetId = value;
    }

    public boolean isSetValueSetId() {
        return (this.valueSetId!= null);
    }

    /**
     * Gets the value of the clearSourceValueSet property.
     * 
     */
    public boolean isClearSourceValueSet() {
        return clearSourceValueSet;
    }

    /**
     * Sets the value of the clearSourceValueSet property.
     * 
     */
    public void setClearSourceValueSet(boolean value) {
        this.clearSourceValueSet = value;
    }

    public boolean isSetClearSourceValueSet() {
        return true;
    }

    /**
     * Gets the value of the forceDeleteStaleCodes property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isForceDeleteStaleCodes() {
        return forceDeleteStaleCodes;
    }

    /**
     * Sets the value of the forceDeleteStaleCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForceDeleteStaleCodes(Boolean value) {
        this.forceDeleteStaleCodes = value;
    }

    public boolean isSetForceDeleteStaleCodes() {
        return (this.forceDeleteStaleCodes!= null);
    }

    /**
     * Gets the value of the createNewVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCreateNewVersion() {
        return createNewVersion;
    }

    /**
     * Sets the value of the createNewVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreateNewVersion(Boolean value) {
        this.createNewVersion = value;
    }

    public boolean isSetCreateNewVersion() {
        return (this.createNewVersion!= null);
    }

    /**
     * Gets the value of the code property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the code property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CD }
     * 
     * 
     */
    public List<CD> getCode() {
        if (code == null) {
            code = new ArrayList<CD>();
        }
        return this.code;
    }

    public boolean isSetCode() {
        return ((this.code!= null)&&(!this.code.isEmpty()));
    }

    public void unsetCode() {
        this.code = null;
    }

}
