//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Response for GetConceptMappingForTwoSourceCodesRequest
 *             
 * 
 * <p>Java class for GetConceptMappingForTwoSourceCodesResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetConceptMappingForTwoSourceCodesResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code_if_found" type="{urn://cts.hl7.org/types}CD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetConceptMappingForTwoSourceCodesResponse", propOrder = {
    "codeIfFound"
})
public class GetConceptMappingForTwoSourceCodesResponse
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "code_if_found")
    protected CD codeIfFound;

    /**
     * Gets the value of the codeIfFound property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getCodeIfFound() {
        return codeIfFound;
    }

    /**
     * Sets the value of the codeIfFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setCodeIfFound(CD value) {
        this.codeIfFound = value;
    }

    public boolean isSetCodeIfFound() {
        return (this.codeIfFound!= null);
    }

}
