//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for binary_or_text complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="binary_or_text">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itemType" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="binaryValue" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="textualValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "binary_or_text", propOrder = {
    "itemType",
    "binaryValue",
    "textualValue"
})
public class BinaryOrText
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected Object itemType;
    @XmlElement(required = true)
    protected byte[] binaryValue;
    protected String textualValue;

    /**
     * Gets the value of the itemType property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getItemType() {
        return itemType;
    }

    /**
     * Sets the value of the itemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setItemType(Object value) {
        this.itemType = value;
    }

    public boolean isSetItemType() {
        return (this.itemType!= null);
    }

    /**
     * Gets the value of the binaryValue property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBinaryValue() {
        return binaryValue;
    }

    /**
     * Sets the value of the binaryValue property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBinaryValue(byte[] value) {
        this.binaryValue = ((byte[]) value);
    }

    public boolean isSetBinaryValue() {
        return (this.binaryValue!= null);
    }

    /**
     * Gets the value of the textualValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextualValue() {
        return textualValue;
    }

    /**
     * Sets the value of the textualValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextualValue(String value) {
        this.textualValue = value;
    }

    public boolean isSetTextualValue() {
        return (this.textualValue!= null);
    }

}
