//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn://cts.hl7.org/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.hl7.cts.types;
