//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import sail.xsd.infrastructure.services.security.RequestSecurity;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{urn:sail:xsd:infrastructure:services:security}RequestSecurity">
 *       &lt;sequence>
 *         &lt;element name="requestCodeValueSetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resultCodeValueSetId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dryRun" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="mappings" type="{urn://cts.hl7.org/types}PanelMappingCollectionType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestCodeValueSetId",
    "resultCodeValueSetId",
    "dryRun",
    "mappings"
})
@XmlRootElement(name = "UploadPanelMappingsRequest")
public class UploadPanelMappingsRequest
    extends RequestSecurity
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(required = true)
    protected String requestCodeValueSetId;
    @XmlElement(required = true)
    protected String resultCodeValueSetId;
    protected Boolean dryRun;
    @XmlElement(required = true)
    protected PanelMappingCollectionType mappings;

    /**
     * Gets the value of the requestCodeValueSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestCodeValueSetId() {
        return requestCodeValueSetId;
    }

    /**
     * Sets the value of the requestCodeValueSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestCodeValueSetId(String value) {
        this.requestCodeValueSetId = value;
    }

    public boolean isSetRequestCodeValueSetId() {
        return (this.requestCodeValueSetId!= null);
    }

    /**
     * Gets the value of the resultCodeValueSetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultCodeValueSetId() {
        return resultCodeValueSetId;
    }

    /**
     * Sets the value of the resultCodeValueSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultCodeValueSetId(String value) {
        this.resultCodeValueSetId = value;
    }

    public boolean isSetResultCodeValueSetId() {
        return (this.resultCodeValueSetId!= null);
    }

    /**
     * Gets the value of the dryRun property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDryRun() {
        return dryRun;
    }

    /**
     * Sets the value of the dryRun property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDryRun(Boolean value) {
        this.dryRun = value;
    }

    public boolean isSetDryRun() {
        return (this.dryRun!= null);
    }

    /**
     * Gets the value of the mappings property.
     * 
     * @return
     *     possible object is
     *     {@link PanelMappingCollectionType }
     *     
     */
    public PanelMappingCollectionType getMappings() {
        return mappings;
    }

    /**
     * Sets the value of the mappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link PanelMappingCollectionType }
     *     
     */
    public void setMappings(PanelMappingCollectionType value) {
        this.mappings = value;
    }

    public boolean isSetMappings() {
        return (this.mappings!= null);
    }

}
