//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConceptChangeCount complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConceptChangeCount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="code_system_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="code_system_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codes_added" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codes_removed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConceptChangeCount", propOrder = {
    "codeSystemId",
    "codeSystemName",
    "codesAdded",
    "codesRemoved"
})
public class ConceptChangeCount
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "code_system_id", required = true)
    protected String codeSystemId;
    @XmlElement(name = "code_system_name", required = true)
    protected String codeSystemName;
    @XmlElement(name = "codes_added")
    protected int codesAdded;
    @XmlElement(name = "codes_removed")
    protected int codesRemoved;

    /**
     * Gets the value of the codeSystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeSystemId() {
        return codeSystemId;
    }

    /**
     * Sets the value of the codeSystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeSystemId(String value) {
        this.codeSystemId = value;
    }

    public boolean isSetCodeSystemId() {
        return (this.codeSystemId!= null);
    }

    /**
     * Gets the value of the codeSystemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeSystemName() {
        return codeSystemName;
    }

    /**
     * Sets the value of the codeSystemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeSystemName(String value) {
        this.codeSystemName = value;
    }

    public boolean isSetCodeSystemName() {
        return (this.codeSystemName!= null);
    }

    /**
     * Gets the value of the codesAdded property.
     * 
     */
    public int getCodesAdded() {
        return codesAdded;
    }

    /**
     * Sets the value of the codesAdded property.
     * 
     */
    public void setCodesAdded(int value) {
        this.codesAdded = value;
    }

    public boolean isSetCodesAdded() {
        return true;
    }

    /**
     * Gets the value of the codesRemoved property.
     * 
     */
    public int getCodesRemoved() {
        return codesRemoved;
    }

    /**
     * Sets the value of the codesRemoved property.
     * 
     */
    public void setCodesRemoved(int value) {
        this.codesRemoved = value;
    }

    public boolean isSetCodesRemoved() {
        return true;
    }

}
