//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import sail.xsd.infrastructure.services.security.RequestSecurity;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{urn:sail:xsd:infrastructure:services:security}RequestSecurity">
 *       &lt;sequence>
 *         &lt;element name="vocab_domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vocabDomain"
})
@XmlRootElement(name = "GetValueSetsForVocabDomainRequest")
public class GetValueSetsForVocabDomainRequest
    extends RequestSecurity
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "vocab_domain", required = true)
    protected String vocabDomain;

    /**
     * Gets the value of the vocabDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocabDomain() {
        return vocabDomain;
    }

    /**
     * Sets the value of the vocabDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocabDomain(String value) {
        this.vocabDomain = value;
    }

    public boolean isSetVocabDomain() {
        return (this.vocabDomain!= null);
    }

}
