//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hl7.cts.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hl7.cts.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UID }
     * 
     */
    public UID createUID() {
        return new UID();
    }

    /**
     * Create an instance of {@link CV }
     * 
     */
    public CV createCV() {
        return new CV();
    }

    /**
     * Create an instance of {@link CR }
     * 
     */
    public CR createCR() {
        return new CR();
    }

    /**
     * Create an instance of {@link ValidateCodeSimpleRequest }
     * 
     */
    public ValidateCodeSimpleRequest createValidateCodeSimpleRequest() {
        return new ValidateCodeSimpleRequest();
    }

    /**
     * Create an instance of {@link ValidateCodeAgainstMultipleCodeSystemsRequest }
     * 
     */
    public ValidateCodeAgainstMultipleCodeSystemsRequest createValidateCodeAgainstMultipleCodeSystemsRequest() {
        return new ValidateCodeAgainstMultipleCodeSystemsRequest();
    }

    /**
     * Create an instance of {@link TranslateCodeSimpleResponse.Error }
     * 
     */
    public TranslateCodeSimpleResponse.Error createTranslateCodeSimpleResponseError() {
        return new TranslateCodeSimpleResponse.Error();
    }

    /**
     * Create an instance of {@link CD }
     * 
     */
    public CD createCD() {
        return new CD();
    }

    /**
     * Create an instance of {@link ConceptChangeCount }
     * 
     */
    public ConceptChangeCount createConceptChangeCount() {
        return new ConceptChangeCount();
    }

    /**
     * Create an instance of {@link GetAllCodesForValueSetResponse }
     * 
     */
    public GetAllCodesForValueSetResponse createGetAllCodesForValueSetResponse() {
        return new GetAllCodesForValueSetResponse();
    }

    /**
     * Create an instance of {@link GetValueSetByIdRequest }
     * 
     */
    public GetValueSetByIdRequest createGetValueSetByIdRequest() {
        return new GetValueSetByIdRequest();
    }

    /**
     * Create an instance of {@link UploadPanelMappingsResponse }
     * 
     */
    public UploadPanelMappingsResponse createUploadPanelMappingsResponse() {
        return new UploadPanelMappingsResponse();
    }

    /**
     * Create an instance of {@link UpdateTerminologyCodesRequest }
     * 
     */
    public UpdateTerminologyCodesRequest createUpdateTerminologyCodesRequest() {
        return new UpdateTerminologyCodesRequest();
    }

    /**
     * Create an instance of {@link ED }
     * 
     */
    public ED createED() {
        return new ED();
    }

    /**
     * Create an instance of {@link GetCodeSystemsByIdResponse }
     * 
     */
    public GetCodeSystemsByIdResponse createGetCodeSystemsByIdResponse() {
        return new GetCodeSystemsByIdResponse();
    }

    /**
     * Create an instance of {@link GetCodesRequest }
     * 
     */
    public GetCodesRequest createGetCodesRequest() {
        return new GetCodesRequest();
    }

    /**
     * Create an instance of {@link ConceptMappingChangeCount }
     * 
     */
    public ConceptMappingChangeCount createConceptMappingChangeCount() {
        return new ConceptMappingChangeCount();
    }

    /**
     * Create an instance of {@link AddOrUpdateValueSetRequest }
     * 
     */
    public AddOrUpdateValueSetRequest createAddOrUpdateValueSetRequest() {
        return new AddOrUpdateValueSetRequest();
    }

    /**
     * Create an instance of {@link PanelMappingCollectionType }
     * 
     */
    public PanelMappingCollectionType createPanelMappingCollectionType() {
        return new PanelMappingCollectionType();
    }

    /**
     * Create an instance of {@link AddOrUpdateValueSetResponse }
     * 
     */
    public AddOrUpdateValueSetResponse createAddOrUpdateValueSetResponse() {
        return new AddOrUpdateValueSetResponse();
    }

    /**
     * Create an instance of {@link ValidateCodeAgainstMultipleCodeSystemsResponse }
     * 
     */
    public ValidateCodeAgainstMultipleCodeSystemsResponse createValidateCodeAgainstMultipleCodeSystemsResponse() {
        return new ValidateCodeAgainstMultipleCodeSystemsResponse();
    }

    /**
     * Create an instance of {@link ST }
     * 
     */
    public ST createST() {
        return new ST();
    }

    /**
     * Create an instance of {@link GetConceptMappingForTwoSourceCodesResponse }
     * 
     */
    public GetConceptMappingForTwoSourceCodesResponse createGetConceptMappingForTwoSourceCodesResponse() {
        return new GetConceptMappingForTwoSourceCodesResponse();
    }

    /**
     * Create an instance of {@link TranslateCodeSimpleResponse }
     * 
     */
    public TranslateCodeSimpleResponse createTranslateCodeSimpleResponse() {
        return new TranslateCodeSimpleResponse();
    }

    /**
     * Create an instance of {@link CodeCount }
     * 
     */
    public CodeCount createCodeCount() {
        return new CodeCount();
    }

    /**
     * Create an instance of {@link ValueSet }
     * 
     */
    public ValueSet createValueSet() {
        return new ValueSet();
    }

    /**
     * Create an instance of {@link BL }
     * 
     */
    public BL createBL() {
        return new BL();
    }

    /**
     * Create an instance of {@link BinaryOrText }
     * 
     */
    public BinaryOrText createBinaryOrText() {
        return new BinaryOrText();
    }

    /**
     * Create an instance of {@link UpdateTerminologyCodesResponse }
     * 
     */
    public UpdateTerminologyCodesResponse createUpdateTerminologyCodesResponse() {
        return new UpdateTerminologyCodesResponse();
    }

    /**
     * Create an instance of {@link CodeSystem }
     * 
     */
    public CodeSystem createCodeSystem() {
        return new CodeSystem();
    }

    /**
     * Create an instance of {@link INT }
     * 
     */
    public INT createINT() {
        return new INT();
    }

    /**
     * Create an instance of {@link UploadPanelMappingsRequest }
     * 
     */
    public UploadPanelMappingsRequest createUploadPanelMappingsRequest() {
        return new UploadPanelMappingsRequest();
    }

    /**
     * Create an instance of {@link ValidateCodeSimpleResponse }
     * 
     */
    public ValidateCodeSimpleResponse createValidateCodeSimpleResponse() {
        return new ValidateCodeSimpleResponse();
    }

    /**
     * Create an instance of {@link AddOrUpdateCodeSystemResponse }
     * 
     */
    public AddOrUpdateCodeSystemResponse createAddOrUpdateCodeSystemResponse() {
        return new AddOrUpdateCodeSystemResponse();
    }

    /**
     * Create an instance of {@link PanelMappingCollectionType.RequestCode.MappedRequestCode }
     * 
     */
    public PanelMappingCollectionType.RequestCode.MappedRequestCode createPanelMappingCollectionTypeRequestCodeMappedRequestCode() {
        return new PanelMappingCollectionType.RequestCode.MappedRequestCode();
    }

    /**
     * Create an instance of {@link GetValueSetsForVocabDomainResponse }
     * 
     */
    public GetValueSetsForVocabDomainResponse createGetValueSetsForVocabDomainResponse() {
        return new GetValueSetsForVocabDomainResponse();
    }

    /**
     * Create an instance of {@link TranslateCodeSimpleRequest }
     * 
     */
    public TranslateCodeSimpleRequest createTranslateCodeSimpleRequest() {
        return new TranslateCodeSimpleRequest();
    }

    /**
     * Create an instance of {@link GetConceptMappingForTwoSourceCodesRequest }
     * 
     */
    public GetConceptMappingForTwoSourceCodesRequest createGetConceptMappingForTwoSourceCodesRequest() {
        return new GetConceptMappingForTwoSourceCodesRequest();
    }

    /**
     * Create an instance of {@link ValueSets }
     * 
     */
    public ValueSets createValueSets() {
        return new ValueSets();
    }

    /**
     * Create an instance of {@link UploadConceptsResponse }
     * 
     */
    public UploadConceptsResponse createUploadConceptsResponse() {
        return new UploadConceptsResponse();
    }

    /**
     * Create an instance of {@link CS }
     * 
     */
    public CS createCS() {
        return new CS();
    }

    /**
     * Create an instance of {@link PanelMappingCollectionType.RequestCode.MappedRequestCode.MappedResultCode }
     * 
     */
    public PanelMappingCollectionType.RequestCode.MappedRequestCode.MappedResultCode createPanelMappingCollectionTypeRequestCodeMappedRequestCodeMappedResultCode() {
        return new PanelMappingCollectionType.RequestCode.MappedRequestCode.MappedResultCode();
    }

    /**
     * Create an instance of {@link AddOrUpdateCodeSystemRequest }
     * 
     */
    public AddOrUpdateCodeSystemRequest createAddOrUpdateCodeSystemRequest() {
        return new AddOrUpdateCodeSystemRequest();
    }

    /**
     * Create an instance of {@link GetValueSetByIdResponse }
     * 
     */
    public GetValueSetByIdResponse createGetValueSetByIdResponse() {
        return new GetValueSetByIdResponse();
    }

    /**
     * Create an instance of {@link GetCodesResponse }
     * 
     */
    public GetCodesResponse createGetCodesResponse() {
        return new GetCodesResponse();
    }

    /**
     * Create an instance of {@link GetCodeSystemsByIdRequest }
     * 
     */
    public GetCodeSystemsByIdRequest createGetCodeSystemsByIdRequest() {
        return new GetCodeSystemsByIdRequest();
    }

    /**
     * Create an instance of {@link GetValueSetsForVocabDomainRequest }
     * 
     */
    public GetValueSetsForVocabDomainRequest createGetValueSetsForVocabDomainRequest() {
        return new GetValueSetsForVocabDomainRequest();
    }

    /**
     * Create an instance of {@link GetCodesResponse.Error }
     * 
     */
    public GetCodesResponse.Error createGetCodesResponseError() {
        return new GetCodesResponse.Error();
    }

    /**
     * Create an instance of {@link UserDetails }
     * 
     */
    public UserDetails createUserDetails() {
        return new UserDetails();
    }

    /**
     * Create an instance of {@link ConceptsToUpload }
     * 
     */
    public ConceptsToUpload createConceptsToUpload() {
        return new ConceptsToUpload();
    }

    /**
     * Create an instance of {@link UploadConceptsRequest }
     * 
     */
    public UploadConceptsRequest createUploadConceptsRequest() {
        return new UploadConceptsRequest();
    }

    /**
     * Create an instance of {@link GetAllCodesForValueSetRequest }
     * 
     */
    public GetAllCodesForValueSetRequest createGetAllCodesForValueSetRequest() {
        return new GetAllCodesForValueSetRequest();
    }

    /**
     * Create an instance of {@link PanelMappingCollectionType.RequestCode }
     * 
     */
    public PanelMappingCollectionType.RequestCode createPanelMappingCollectionTypeRequestCode() {
        return new PanelMappingCollectionType.RequestCode();
    }

    /**
     * Create an instance of {@link ConceptsToUploadBatch }
     * 
     */
    public ConceptsToUploadBatch createConceptsToUploadBatch() {
        return new ConceptsToUploadBatch();
    }

}
