//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn://cts.hl7.org/types}UploadConceptsResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "uploadConceptsResponse"
})
@XmlRootElement(name = "UploadPanelMappingsResponse")
public class UploadPanelMappingsResponse
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "UploadConceptsResponse", required = true)
    protected UploadConceptsResponse uploadConceptsResponse;

    /**
     * Gets the value of the uploadConceptsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link UploadConceptsResponse }
     *     
     */
    public UploadConceptsResponse getUploadConceptsResponse() {
        return uploadConceptsResponse;
    }

    /**
     * Sets the value of the uploadConceptsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link UploadConceptsResponse }
     *     
     */
    public void setUploadConceptsResponse(UploadConceptsResponse value) {
        this.uploadConceptsResponse = value;
    }

    public boolean isSetUploadConceptsResponse() {
        return (this.uploadConceptsResponse!= null);
    }

}
