//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.13 at 04:02:04 PM EST 
//


package org.hl7.cts.types;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import sail.xsd.infrastructure.services.security.RequestSecurity;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{urn:sail:xsd:infrastructure:services:security}RequestSecurity">
 *       &lt;sequence>
 *         &lt;element name="dryRun" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{urn://cts.hl7.org/types}UserDetails"/>
 *         &lt;element ref="{urn://cts.hl7.org/types}ConceptsToUpload" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn://cts.hl7.org/types}ConceptsToUploadBatch" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dryRun",
    "userDetails",
    "conceptsToUpload",
    "conceptsToUploadBatch"
})
@XmlRootElement(name = "UploadConceptsRequest")
public class UploadConceptsRequest
    extends RequestSecurity
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected Boolean dryRun;
    @XmlElement(name = "UserDetails", required = true)
    protected UserDetails userDetails;
    @XmlElement(name = "ConceptsToUpload")
    protected List<ConceptsToUpload> conceptsToUpload;
    @XmlElement(name = "ConceptsToUploadBatch")
    protected List<ConceptsToUploadBatch> conceptsToUploadBatch;

    /**
     * Gets the value of the dryRun property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDryRun() {
        return dryRun;
    }

    /**
     * Sets the value of the dryRun property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDryRun(Boolean value) {
        this.dryRun = value;
    }

    public boolean isSetDryRun() {
        return (this.dryRun!= null);
    }

    /**
     * Gets the value of the userDetails property.
     * 
     * @return
     *     possible object is
     *     {@link UserDetails }
     *     
     */
    public UserDetails getUserDetails() {
        return userDetails;
    }

    /**
     * Sets the value of the userDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDetails }
     *     
     */
    public void setUserDetails(UserDetails value) {
        this.userDetails = value;
    }

    public boolean isSetUserDetails() {
        return (this.userDetails!= null);
    }

    /**
     * Gets the value of the conceptsToUpload property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conceptsToUpload property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConceptsToUpload().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConceptsToUpload }
     * 
     * 
     */
    public List<ConceptsToUpload> getConceptsToUpload() {
        if (conceptsToUpload == null) {
            conceptsToUpload = new ArrayList<ConceptsToUpload>();
        }
        return this.conceptsToUpload;
    }

    public boolean isSetConceptsToUpload() {
        return ((this.conceptsToUpload!= null)&&(!this.conceptsToUpload.isEmpty()));
    }

    public void unsetConceptsToUpload() {
        this.conceptsToUpload = null;
    }

    /**
     * Gets the value of the conceptsToUploadBatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conceptsToUploadBatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConceptsToUploadBatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConceptsToUploadBatch }
     * 
     * 
     */
    public List<ConceptsToUploadBatch> getConceptsToUploadBatch() {
        if (conceptsToUploadBatch == null) {
            conceptsToUploadBatch = new ArrayList<ConceptsToUploadBatch>();
        }
        return this.conceptsToUploadBatch;
    }

    public boolean isSetConceptsToUploadBatch() {
        return ((this.conceptsToUploadBatch!= null)&&(!this.conceptsToUploadBatch.isEmpty()));
    }

    public void unsetConceptsToUploadBatch() {
        this.conceptsToUploadBatch = null;
    }

}
